version: '3'

services:
  nodo1:
    image: hadoophdfs
    container_name: nodo1_hdfs
    hostname: nodo1
    restart: unless-stopped
    environment:
      - NODE_NAME=nodo1
      - CONFIG_PATH=/mnt/config
      - SINGLE_NODE=true
    volumes:
      - ./nodes/shared:/mnt/shared
      - ./config:/mnt/config
    ports:
      - "22:22"
      - "9000:9000"
      - "50070:50070"
      - "50010:50010"
      - "50020:50020"
      - "50075:50075"
      - "50090:50090"
      - "8020:8020"
      - "9870:9870"
      - "8088:8088"
